Tcp listen backlog
heroku/barnes pull request #2
Opened 2017-09-14 23:37 UTC by apg

Grab the TCP listen backlog from proc on Linux.

2017-09-14 23:38 UTC, apg commented
Sorry about the background-reporter being in here too. It's pretty easy to ignore some of that as the last commit just adds 3 files.

2017-09-15 00:14 UTC, apg commented
Connects to heroku/opex-team#241

2017-09-15 20:05 UTC, schneems requested changes
Some minor style nits. There are some places where we could clean up logic. There's lots of room for personal opinion on style though. lining up equals and hashes helps with readability a lot.

My biggest ask is possibly for more docs. In my dream world each of these classes would have a small blurb saying what they do and then a tiny example. It's not 100% critical, but helps a ton if the next person to maintain this code isn't either one of us.

There is some hex math being done. If you could document how that works or why it works, or link to some other documentation about what exactly you're doing that would be amazing.

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +      def start(state, counters, gauges)
Are we using this method anywhere? Can we get rid of it?

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +        end
It looks like this is the only place we're actively using the `@pid`. Instead of storing the @pid and then building a new string every time, could we instead do this calculation once in the initializer?

Also you don't need the `then` keyword.

```
def initialize(pid = 'net')
  @basefile = "/proc/#{pid}/"
end
```

I'm not sure if you want to do any kind of type checking here. I.e. if pid is entered as a non integer and not "net" then maybe we want to error?

```
if pid == "net" || pid = Integer(pid)
  raise ArgumentError, "You entered #{pid} which is not an integer or 'net'"
```

On the flip side since we're opening the file later I guess it will fail if it doesn't exist, so that's reasonable enough.

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +          ProcTCP.new(File.open(basefile + name)).by(:st => TCP_SYN_RECV) do |entry|
You can do `File.join(basefile, name)` to ensure that you don't accidentally have a double slash or a missing slash. Alternatively you could use a pathname object

```
require 'pathname'
PathName.new("/proc/#{pid}").join(name).open
```

On a style note `:st => TCP_SYN_RECV` is usually done as `st: TCP_SYN_RECV`. If the keys are symbols.

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +        @pid = pid
I don't think we're using this @pid variable in this class

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +          :inode => pieces[13].to_i,
Style nit, I would line these up and move over to 1.9.3 style hashes:

```
local_addr:  toip(pieces[1]),
local_port:  pieces[2].hex,
remote_addr: toip(pieces[3]),
remote_port: pieces[4].hex,
st:          pieces[5].hex,
tx_queue:    pieces[6].to_i,
rx_queue:    pieces[7].to_i,
tr:          pieces[8].hex,
tm_when:     pieces[9],
retrnsmt:    pieces[10],
uid:         pieces[11].to_i,
timeout:     pieces[12].to_i,
inode:       pieces[13].to_i,
```

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +      def toip(piece)
If you only have one private method I prefer to do the private inline

```
private def toip(piece)
```

This works because `def toip(piece)` returns back a symbol `:toip` and the `private` keyword takes a symbol so it only makes that one method private.

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +          "#{i & 0xff}.#{(i >> 8) & 0xff}.#{(i >> 16) & 0xff}.#{(i >> 24) & 0xff}"
Can you add some docs on what exactly this method is doing? This is hex magic as far as i'm concerned

2017-09-15 20:05 UTC, schneems commented on lib/trashed/instruments/backlog.rb
> +    TCP_CLOSING = 11
Can you line up the equals?

```
TCP_ESTABLISHED = 1
TCP_SYN_SENT    = 2
TCP_SYN_RECV    = 3
TCP_FIN_WAIT1   = 4
TCP_FIN_WAIT2   = 5
TCP_TIME_WAIT   = 6
TCP_CLOSE       = 7
TCP_CLOSE_WAIT  = 8
TCP_LAST_ACK    = 9
TCP_LISTEN      = 10
TCP_CLOSING     = 11
```

2017-09-15 20:05 UTC, schneems commented on test/backlog_test.rb
> +    end
It would be longer but I would probably blow these up into two separate tests. It's a bit more verbose, but slightly more clear from a readability standpoint what's being tested:

```ruby
count = 0
Trashed::Instruments::ProcTCP.new(tcp).by(:st => Trashed::Instruments::TCP_LISTEN) do |entry|
  count += 1
end
assert_equal 2, count

count = 0
Trashed::Instruments::ProcTCP.new(tcp).by(:st => Trashed::Instruments::TCP_ESTABLISHED) do |entry|
  count += 1
end
assert_equal 7, count
```

2017-09-15 20:05 UTC, schneems commented on test/backlog_test.rb
> +     StringIO.new(<<-HEREDOC
Thank you for putting these in here. Will make maintenance much easier.

2017-09-15 20:05 UTC, schneems commented on lib/trashed/reporter.rb
> +    end
Blank method?

2017-09-15 23:25 UTC, apg commented on lib/trashed/instruments/backlog.rb
> +      def start(state, counters, gauges)
meter.rb has a `if instrument.respond_to?(:start)` so it's safe to remove.

2017-09-15 23:26 UTC, apg commented on lib/trashed/instruments/backlog.rb
> +        end
Good call on this.

2017-09-15 23:27 UTC, apg commented on lib/trashed/instruments/backlog.rb
> +        @pid = pid
Good catch! This got refactored for testing, and ...

2017-09-25 18:48 UTC, apg commented on lib/trashed/reporter.rb
> +    end
The base class has a thing that is utilized in the RackReporter (which is being killed in this fork).

2017-09-27 18:17 UTC, apg commented
This PR is taking on a life of it's own, and I'm going to merge and close it. Will Follow up with some additional PRs that address other things.

2017-09-27 18:17 UTC, merged